### PR TITLE
Rename raft packages

### PR DESCRIPTION
**Pull request by cole-miller**
Signed-off-by: Cole Miller <cole.miller@canonical.com>

### CODE REVIEW

**Comment by cole-miller** [comment]
I have taken the approach in this PR of renaming only the packages themselves; the installed files keep their names, and the .pc file is unchanged. That means it's not possible to install our packages simultaneously with those from CowSQL. I doubt this will be a problem in practice, and it means updating the name in many fewer places.

**Comment by tomponline** [comment]
Do we need to update our ci env too?

**Comment by cole-miller** [comment]
@tomponline It's my first time reading the LXD CI so I could be wrong but I don't think so. AFAICT you do add the PPA (which will not change its name) but you don't `apt install raft` at any point; ~~the Makefile grabs the dqlite and raft sources straight from GitHub~~ instead you depend on libdqlite-dev, the name of which won't change.

**Comment by MathieuBordere** [comment]
I think we also need to rename `SONAME` and `SOPKG` in rules (and other places where libraft is used), otherwise it will also clash with the other package I think. But then those names are no longer matching with the library names in the raft repos, so we'd need to change them there too.

**Comment by cole-miller** [comment]
@MathieuBordere I don't think we should rename the .pc file, SONAME, etc. We should just add a `Conflicts:` to each package that indicates that it's not compatible with CowSQL's raft. If we try to rename our library everywhere it's a much bigger headache for I think not much gain

**Comment by MathieuBordere** [comment]
> @MathieuBordere I don't think we should rename the .pc file, SONAME, etc. We should just add a `Conflicts:` to this source (or each package) that indicates that it's not compatible with CowSQL's raft. If we try to rename our library everywhere it's a much bigger headache for I think not much gain

yeah, rename was a brute-force solution because I didn't know of the existence of `Conflicts:` :-)

**Comment by MathieuBordere** [comment]
Can we wildcard the `Conflicts:` field? If they release a version 4, we will be in conflict again I think.

**Comment by cole-miller** [comment]
I don't think it's possible to wildcard the RHS of `Conflicts:`, it has to be a proper package name. You can specify a range of versions but we conflict with every version of `libraft3` so that's not useful.

**Comment by MathieuBordere** [comment]
> I don't think it's possible to wildcard the RHS of `Conflicts:`, it has to be a proper package name. You can specify a range of versions but we conflict with every version of `libraft3` so that's not useful.

Okay, let's keep an eye on it then.

**Pull request merged**
